version: 2

models:
  - name: d_user_name
    description: "TODO: describe d_user_name"
    columns:
      - name: id
        description: "Primary key"
        tests:
          - unique
          - not_null

