version: 2

models:
  - name: f_bt
    description: "TODO: describe f_bt"
    columns:
      - name: id
        description: "Primary key"
        tests:
          - unique
          - not_null
  - name: new_bt
    description: "TODO: describe new_bt"
    columns:
      - name: id
        description: "Primary key"
        tests:
          - unique
          - not_null

