# version: 2

# models:
#   - name: f_sessions_final
#     description: "Merged fact table combining live and on-demand sessions with scenario and learner details."
#     tests:
#       - dbt_utils.unique_combination_of_columns:
#           arguments:
#             combination_of_columns:
#               - id
#               - learner_id
  - name: f_client_db
    description: "TODO: describe f_client_db"
    columns:
      - name: id
        description: "Primary key"
        tests:
          - unique
          - not_null
  - name: f_client
    description: "TODO: describe f_client"
    columns:
      - name: id
        description: "Primary key"
        tests:
          - unique
          - not_null

